spring.application.name=api-gestao-veiculos

# PostgreSQL - Configuração Local
spring.datasource.url=jdbc:postgresql://localhost:5432/api_veiculos
spring.datasource.username=postgres
spring.datasource.password=sua_senha_aqui
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL - Configuração Produção (Render)
# spring.datasource.url=${DATABASE_URL}
# spring.datasource.username=${DATABASE_USERNAME}
# spring.datasource.password=${DATABASE_PASSWORD}
# spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.show-sql=false

# Springdoc - Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.api-docs.path=/v3/api-docs

# JWT
jwt.secret=${JWT_SECRET:Y2hhdGdwdHJhcGFzc3dvcmR0ZXN0aW5namV3ZWxhcHByb3ZlY2hhdGdwdHJhcGFzc3dvcmR0}
jwt.expiration=86400000
